/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './EndPointDetailComponent';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './EndPointService';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/common/src/location/location';
import * as import11 from 'ng2-bootstrap/tabs/tabset.component';
import * as import12 from '../../node_modules/ng2-bootstrap/tabs/tabset.component.ngfactory';
import * as import13 from '../../node_modules/ng2-bootstrap/tabs/tab.directive.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import16 from 'ng2-bootstrap/accordion/accordion.component';
import * as import17 from '../../node_modules/ng2-bootstrap/accordion/accordion.component.ngfactory';
import * as import18 from 'ng2-bootstrap/accordion/accordion-group.component';
import * as import19 from '../../node_modules/ng2-bootstrap/accordion/accordion-group.component.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/checkbox_value_accessor.ngfactory';
import * as import24 from '../ApiKey/ApiKeyListComponent';
import * as import25 from '../ApiKey/ApiKeyListComponent.ngfactory';
import * as import26 from '@angular/core/src/linker/view_container';
import * as import27 from '@angular/core/src/change_detection/change_detection_util';
import * as import28 from 'ng2-bootstrap/tabs/tabset.config';
import * as import29 from 'ng2-bootstrap/accordion/accordion.config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from '@angular/forms/src/directives/default_value_accessor';
import * as import32 from '@angular/forms/src/directives/validators';
import * as import33 from '@angular/forms/src/validators';
import * as import34 from '@angular/forms/src/directives/control_value_accessor';
import * as import35 from '@angular/forms/src/directives/ng_model';
import * as import36 from '@angular/forms/src/directives/ng_control';
import * as import37 from '@angular/forms/src/directives/ng_control_status';
import * as import38 from '@angular/forms/src/directives/checkbox_value_accessor';
import * as import39 from '@angular/forms/src/directives/ng_form';
import * as import40 from '@angular/forms/src/directives/control_container';
import * as import41 from 'ng2-bootstrap/tabs/tab.directive';
import * as import42 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import43 from '@angular/core/src/linker/template_ref';
import * as import44 from '@angular/common/src/directives/ng_if';
export class Wrapper_EndPointDetailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EndPointDetailComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.EndPointDetailComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EndPointDetailComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EndPointDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EndPointDetailComponent>;
  _EndPointDetailComponent_0_3:Wrapper_EndPointDetailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EndPointDetailComponent_Host0,renderType_EndPointDetailComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'endpoint-detail',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EndPointDetailComponent0(this.viewUtils,this,0,this._el_0);
    this._EndPointDetailComponent_0_3 = new Wrapper_EndPointDetailComponent(this.injectorGet(import8.EndPointService,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex),this.injectorGet(import10.Location,this.parentIndex));
    this.compView_0.create(this._EndPointDetailComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EndPointDetailComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EndPointDetailComponent) && (0 === requestNodeIndex))) { return this._EndPointDetailComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EndPointDetailComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EndPointDetailComponentNgFactory:import7.ComponentFactory<import0.EndPointDetailComponent> = new import7.ComponentFactory<import0.EndPointDetailComponent>('endpoint-detail',View_EndPointDetailComponent_Host0,import0.EndPointDetailComponent);
const styles_EndPointDetailComponent:any[] = ([] as any[]);
class View_EndPointDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import11.TabsetComponent>;
  _TabsetComponent_2_3:import12.Wrapper_TabsetComponent;
  _text_3:any;
  _el_4:any;
  _TabDirective_4_3:import13.Wrapper_TabDirective;
  _text_5:any;
  _el_6:any;
  _NgForm_6_3:import14.Wrapper_NgForm;
  _ControlContainer_6_4:any;
  _NgControlStatusGroup_6_5:import15.Wrapper_NgControlStatusGroup;
  _text_7:any;
  _el_8:any;
  compView_8:import1.AppView<import16.AccordionComponent>;
  _AccordionComponent_8_3:import17.Wrapper_AccordionComponent;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import18.AccordionPanelComponent>;
  _AccordionPanelComponent_10_3:import19.Wrapper_AccordionPanelComponent;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import20.Wrapper_DefaultValueAccessor;
  _RequiredValidator_31_4:import21.Wrapper_RequiredValidator;
  _NG_VALIDATORS_31_5:any[];
  _NG_VALUE_ACCESSOR_31_6:any[];
  _NgModel_31_7:import22.Wrapper_NgModel;
  _NgControl_31_8:any;
  _NgControlStatus_31_9:import15.Wrapper_NgControlStatus;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _CheckboxControlValueAccessor_42_3:import23.Wrapper_CheckboxControlValueAccessor;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _NgModel_42_5:import22.Wrapper_NgModel;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import15.Wrapper_NgControlStatus;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  compView_47:import1.AppView<import18.AccordionPanelComponent>;
  _AccordionPanelComponent_47_3:import19.Wrapper_AccordionPanelComponent;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _DefaultValueAccessor_56_3:import20.Wrapper_DefaultValueAccessor;
  _RequiredValidator_56_4:import21.Wrapper_RequiredValidator;
  _NG_VALIDATORS_56_5:any[];
  _NG_VALUE_ACCESSOR_56_6:any[];
  _NgModel_56_7:import22.Wrapper_NgModel;
  _NgControl_56_8:any;
  _NgControlStatus_56_9:import15.Wrapper_NgControlStatus;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _DefaultValueAccessor_67_3:import20.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_67_4:any[];
  _NgModel_67_5:import22.Wrapper_NgModel;
  _NgControl_67_6:any;
  _NgControlStatus_67_7:import15.Wrapper_NgControlStatus;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _DefaultValueAccessor_78_3:import20.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_78_4:any[];
  _NgModel_78_5:import22.Wrapper_NgModel;
  _NgControl_78_6:any;
  _NgControlStatus_78_7:import15.Wrapper_NgControlStatus;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _TabDirective_95_3:import13.Wrapper_TabDirective;
  _text_96:any;
  _el_97:any;
  compView_97:import1.AppView<import24.ApiKeyListComponent>;
  _ApiKeyListComponent_97_3:import25.Wrapper_ApiKeyListComponent;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  /*private*/ _expr_145:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import26.ViewContainer) {
    super(View_EndPointDetailComponent1,renderType_EndPointDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_145 = import27.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'tabset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import12.View_TabsetComponent0(this.viewUtils,this,2,this._el_2);
    this._TabsetComponent_2_3 = new import12.Wrapper_TabsetComponent(this.parentView.injectorGet(import28.TabsetConfig,this.parentIndex));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'tab',new import3.InlineArray2(2,'active','true'),(null as any));
    this._TabDirective_4_3 = new import13.Wrapper_TabDirective(this._TabsetComponent_2_3.context);
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'form',new import3.InlineArray2(2,'class','form-horizontal'),(null as any));
    this._NgForm_6_3 = new import14.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_6_4 = this._NgForm_6_3.context;
    this._NgControlStatusGroup_6_5 = new import15.Wrapper_NgControlStatusGroup(this._ControlContainer_6_4);
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'accordion',new import3.InlineArray2(2,'role','tablist'),(null as any));
    this.compView_8 = new import17.View_AccordionComponent0(this.viewUtils,this,8,this._el_8);
    this._AccordionComponent_8_3 = new import17.Wrapper_AccordionComponent(this.parentView.injectorGet(import29.AccordionConfig,this.parentIndex));
    this._text_9 = this.renderer.createText((null as any),'\n\n          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,(null as any),'accordion-group',new import3.InlineArray4(4,'heading','Basic','isOpen','true'),(null as any));
    this.compView_10 = new import19.View_AccordionPanelComponent0(this.viewUtils,this,10,this._el_10);
    this._AccordionPanelComponent_10_3 = new import19.Wrapper_AccordionPanelComponent(this._AccordionComponent_8_3.context);
    this._text_11 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n              ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'label',new import3.InlineArray2(2,'class','col-sm-2 control-label'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'ID',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n              ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','col-sm-10'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'p',new import3.InlineArray2(2,'class','form-control-static'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n              ',(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n              ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'label',new import3.InlineArray4(4,'class','col-sm-2 control-label','for','title'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Title',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n              ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','col-sm-10'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'input',new import3.InlineArray16(10,'class','form-control','name','title','placeholder','title','required','true','type','text'),(null as any));
    this._DefaultValueAccessor_31_3 = new import20.Wrapper_DefaultValueAccessor(this.renderer,new import30.ElementRef(this._el_31));
    this._RequiredValidator_31_4 = new import21.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_31_5 = [this._RequiredValidator_31_4.context];
    this._NG_VALUE_ACCESSOR_31_6 = [this._DefaultValueAccessor_31_3.context];
    this._NgModel_31_7 = new import22.Wrapper_NgModel(this._ControlContainer_6_4,this._NG_VALIDATORS_31_5,(null as any),this._NG_VALUE_ACCESSOR_31_6);
    this._NgControl_31_8 = this._NgModel_31_7.context;
    this._NgControlStatus_31_9 = new import15.Wrapper_NgControlStatus(this._NgControl_31_8);
    this._text_32 = this.renderer.createText(this._el_29,'\n              ',(null as any));
    this._text_33 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n              ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray4(4,'class','col-sm-2 control-label','for','title'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Enabled',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n              ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','col-sm-10'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'input',new import3.InlineArray8(8,'class','form-control','name','enabled','placeholder','enabled','type','checkbox'),(null as any));
    this._CheckboxControlValueAccessor_42_3 = new import23.Wrapper_CheckboxControlValueAccessor(this.renderer,new import30.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._CheckboxControlValueAccessor_42_3.context];
    this._NgModel_42_5 = new import22.Wrapper_NgModel(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._NgModel_42_5.context;
    this._NgControlStatus_42_7 = new import15.Wrapper_NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_40,'\n              ',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n          ',(null as any));
    this.compView_10.create(this._AccordionPanelComponent_10_3.context);
    this._text_46 = this.renderer.createText((null as any),'\n          \n          ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,(null as any),'accordion-group',new import3.InlineArray4(4,'heading','Upstream Service','isOpen','true'),(null as any));
    this.compView_47 = new import19.View_AccordionPanelComponent0(this.viewUtils,this,47,this._el_47);
    this._AccordionPanelComponent_47_3 = new import19.Wrapper_AccordionPanelComponent(this._AccordionComponent_8_3.context);
    this._text_48 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n              ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'label',new import3.InlineArray4(4,'class','col-sm-2 control-label','for','upstreamUrl'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Upstream URL',(null as any));
    this._text_53 = this.renderer.createText(this._el_49,'\n              ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_49,'div',new import3.InlineArray2(2,'class','col-sm-10'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'input',new import3.InlineArray16(10,'class','form-control','name','upstreamUrl','placeholder','http://server.com/','required','true','type','url'),(null as any));
    this._DefaultValueAccessor_56_3 = new import20.Wrapper_DefaultValueAccessor(this.renderer,new import30.ElementRef(this._el_56));
    this._RequiredValidator_56_4 = new import21.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_56_5 = [this._RequiredValidator_56_4.context];
    this._NG_VALUE_ACCESSOR_56_6 = [this._DefaultValueAccessor_56_3.context];
    this._NgModel_56_7 = new import22.Wrapper_NgModel(this._ControlContainer_6_4,this._NG_VALIDATORS_56_5,(null as any),this._NG_VALUE_ACCESSOR_56_6);
    this._NgControl_56_8 = this._NgModel_56_7.context;
    this._NgControlStatus_56_9 = new import15.Wrapper_NgControlStatus(this._NgControl_56_8);
    this._text_57 = this.renderer.createText(this._el_54,'\n              ',(null as any));
    this._text_58 = this.renderer.createText(this._el_49,'\n            ',(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'\n              ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_60,'label',new import3.InlineArray4(4,'class','col-sm-2 control-label','for','upstreamUsername'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Upstream Username',(null as any));
    this._text_64 = this.renderer.createText(this._el_60,'\n              ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_60,'div',new import3.InlineArray2(2,'class','col-sm-10'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n                ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'input',new import3.InlineArray8(8,'class','form-control','name','upstreamUsername','placeholder','Username','type','text'),(null as any));
    this._DefaultValueAccessor_67_3 = new import20.Wrapper_DefaultValueAccessor(this.renderer,new import30.ElementRef(this._el_67));
    this._NG_VALUE_ACCESSOR_67_4 = [this._DefaultValueAccessor_67_3.context];
    this._NgModel_67_5 = new import22.Wrapper_NgModel(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_67_4);
    this._NgControl_67_6 = this._NgModel_67_5.context;
    this._NgControlStatus_67_7 = new import15.Wrapper_NgControlStatus(this._NgControl_67_6);
    this._text_68 = this.renderer.createText(this._el_65,'\n              ',(null as any));
    this._text_69 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n              ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_71,'label',new import3.InlineArray4(4,'class','col-sm-2 control-label','for','upstreamPassword'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'Upstream Password',(null as any));
    this._text_75 = this.renderer.createText(this._el_71,'\n              ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_71,'div',new import3.InlineArray2(2,'class','col-sm-10'),(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'\n                ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_76,'input',new import3.InlineArray8(8,'class','form-control','name','upstreamPassword','placeholder','Password','type','password'),(null as any));
    this._DefaultValueAccessor_78_3 = new import20.Wrapper_DefaultValueAccessor(this.renderer,new import30.ElementRef(this._el_78));
    this._NG_VALUE_ACCESSOR_78_4 = [this._DefaultValueAccessor_78_3.context];
    this._NgModel_78_5 = new import22.Wrapper_NgModel(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_78_4);
    this._NgControl_78_6 = this._NgModel_78_5.context;
    this._NgControlStatus_78_7 = new import15.Wrapper_NgControlStatus(this._NgControl_78_6);
    this._text_79 = this.renderer.createText(this._el_76,'\n              ',(null as any));
    this._text_80 = this.renderer.createText(this._el_71,'\n            ',(null as any));
    this._text_81 = this.renderer.createText((null as any),'\n          ',(null as any));
    this.compView_47.create(this._AccordionPanelComponent_47_3.context);
    this._text_82 = this.renderer.createText((null as any),'\n          \n        ',(null as any));
    this.compView_8.create(this._AccordionComponent_8_3.context);
    this._text_83 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray4(4,'class','btn-toolbar','role','toolbar'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_84,'a',new import3.InlineArray4(4,'class','btn btn-sm btn-danger','role','button'),(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'Cancel',(null as any));
    this._text_88 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_84,'a',new import3.InlineArray4(4,'class','btn btn-sm btn-primary','role','button'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'Save',(null as any));
    this._text_91 = this.renderer.createText(this._el_84,'\n        ',(null as any));
    this._text_92 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_93 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_94 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,(null as any),'tab',new import3.InlineArray2(2,'heading','Api Keys'),(null as any));
    this._TabDirective_95_3 = new import13.Wrapper_TabDirective(this._TabsetComponent_2_3.context);
    this._text_96 = this.renderer.createText(this._el_95,'\n      ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_95,'apiKey-list',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_97 = new import25.View_ApiKeyListComponent0(this.viewUtils,this,97,this._el_97);
    this._ApiKeyListComponent_97_3 = new import25.Wrapper_ApiKeyListComponent();
    this.compView_97.create(this._ApiKeyListComponent_97_3.context);
    this._text_98 = this.renderer.createText(this._el_95,'\n    ',(null as any));
    this._text_99 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_2.create(this._TabsetComponent_2_3.context);
    this._text_100 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_31));
    this._NgModel_31_7.subscribe(this,this.eventHandler(this.handleEvent_31),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_42));
    this._NgModel_42_5.subscribe(this,this.eventHandler(this.handleEvent_42),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_56,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_56));
    this._NgModel_56_7.subscribe(this,this.eventHandler(this.handleEvent_56),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_67,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_67));
    this._NgModel_67_5.subscribe(this,this.eventHandler(this.handleEvent_67),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_78,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_78));
    this._NgModel_78_5.subscribe(this,this.eventHandler(this.handleEvent_78),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_86,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_86));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_89,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_89));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3.context; }
    if (((token === import32.RequiredValidator) && (31 === requestNodeIndex))) { return this._RequiredValidator_31_4.context; }
    if (((token === import33.NG_VALIDATORS) && (31 === requestNodeIndex))) { return this._NG_VALIDATORS_31_5; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_6; }
    if (((token === import35.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_7.context; }
    if (((token === import36.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_8; }
    if (((token === import37.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_9.context; }
    if (((token === import38.CheckboxControlValueAccessor) && (42 === requestNodeIndex))) { return this._CheckboxControlValueAccessor_42_3.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import35.NgModel) && (42 === requestNodeIndex))) { return this._NgModel_42_5.context; }
    if (((token === import36.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_6; }
    if (((token === import37.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_7.context; }
    if (((token === import18.AccordionPanelComponent) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._AccordionPanelComponent_10_3.context; }
    if (((token === import31.DefaultValueAccessor) && (56 === requestNodeIndex))) { return this._DefaultValueAccessor_56_3.context; }
    if (((token === import32.RequiredValidator) && (56 === requestNodeIndex))) { return this._RequiredValidator_56_4.context; }
    if (((token === import33.NG_VALIDATORS) && (56 === requestNodeIndex))) { return this._NG_VALIDATORS_56_5; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (56 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_56_6; }
    if (((token === import35.NgModel) && (56 === requestNodeIndex))) { return this._NgModel_56_7.context; }
    if (((token === import36.NgControl) && (56 === requestNodeIndex))) { return this._NgControl_56_8; }
    if (((token === import37.NgControlStatus) && (56 === requestNodeIndex))) { return this._NgControlStatus_56_9.context; }
    if (((token === import31.DefaultValueAccessor) && (67 === requestNodeIndex))) { return this._DefaultValueAccessor_67_3.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (67 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_67_4; }
    if (((token === import35.NgModel) && (67 === requestNodeIndex))) { return this._NgModel_67_5.context; }
    if (((token === import36.NgControl) && (67 === requestNodeIndex))) { return this._NgControl_67_6; }
    if (((token === import37.NgControlStatus) && (67 === requestNodeIndex))) { return this._NgControlStatus_67_7.context; }
    if (((token === import31.DefaultValueAccessor) && (78 === requestNodeIndex))) { return this._DefaultValueAccessor_78_3.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (78 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_78_4; }
    if (((token === import35.NgModel) && (78 === requestNodeIndex))) { return this._NgModel_78_5.context; }
    if (((token === import36.NgControl) && (78 === requestNodeIndex))) { return this._NgControl_78_6; }
    if (((token === import37.NgControlStatus) && (78 === requestNodeIndex))) { return this._NgControlStatus_78_7.context; }
    if (((token === import18.AccordionPanelComponent) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._AccordionPanelComponent_47_3.context; }
    if (((token === import16.AccordionComponent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._AccordionComponent_8_3.context; }
    if (((token === import39.NgForm) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 92)))) { return this._NgForm_6_3.context; }
    if (((token === import40.ControlContainer) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 92)))) { return this._ControlContainer_6_4; }
    if (((token === import37.NgControlStatusGroup) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 92)))) { return this._NgControlStatusGroup_6_5.context; }
    if (((token === import41.TabDirective) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._TabDirective_4_3.context; }
    if (((token === import24.ApiKeyListComponent) && (97 === requestNodeIndex))) { return this._ApiKeyListComponent_97_3.context; }
    if (((token === import41.TabDirective) && ((95 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._TabDirective_95_3.context; }
    if (((token === import11.TabsetComponent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._TabsetComponent_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TabsetComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = import3.inlineInterpolate(1,'End Point: ',this.parentView.context.endPoint.id,'');
    this._TabDirective_4_3.check_heading(currVal_4_0_0,throwOnChange,false);
    const currVal_4_0_1:any = 'true';
    this._TabDirective_4_3.check_active(currVal_4_0_1,throwOnChange,false);
    this._TabDirective_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._NgForm_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._NgControlStatusGroup_6_5.ngDoCheck(this,this._el_6,throwOnChange);
    this._AccordionComponent_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_10_0_0:any = 'Basic';
    this._AccordionPanelComponent_10_3.check_heading(currVal_10_0_0,throwOnChange,false);
    const currVal_10_0_1:any = 'true';
    this._AccordionPanelComponent_10_3.check_isOpen(currVal_10_0_1,throwOnChange,false);
    this._AccordionPanelComponent_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    this._DefaultValueAccessor_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_1_0:any = 'true';
    this._RequiredValidator_31_4.check_required(currVal_31_1_0,throwOnChange,false);
    this._RequiredValidator_31_4.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_2_0:any = 'title';
    this._NgModel_31_7.check_name(currVal_31_2_0,throwOnChange,false);
    const currVal_31_2_1:any = this.parentView.context.endPoint.title;
    this._NgModel_31_7.check_model(currVal_31_2_1,throwOnChange,false);
    this._NgModel_31_7.ngDoCheck(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.ngDoCheck(this,this._el_31,throwOnChange);
    this._CheckboxControlValueAccessor_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_1_0:any = 'enabled';
    this._NgModel_42_5.check_name(currVal_42_1_0,throwOnChange,false);
    const currVal_42_1_1:any = this.parentView.context.endPoint.enabled;
    this._NgModel_42_5.check_model(currVal_42_1_1,throwOnChange,false);
    this._NgModel_42_5.ngDoCheck(this,this._el_42,throwOnChange);
    this._NgControlStatus_42_7.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_47_0_0:any = 'Upstream Service';
    this._AccordionPanelComponent_47_3.check_heading(currVal_47_0_0,throwOnChange,false);
    const currVal_47_0_1:any = 'true';
    this._AccordionPanelComponent_47_3.check_isOpen(currVal_47_0_1,throwOnChange,false);
    this._AccordionPanelComponent_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    this._DefaultValueAccessor_56_3.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_56_1_0:any = 'true';
    this._RequiredValidator_56_4.check_required(currVal_56_1_0,throwOnChange,false);
    this._RequiredValidator_56_4.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_56_2_0:any = 'upstreamUrl';
    this._NgModel_56_7.check_name(currVal_56_2_0,throwOnChange,false);
    const currVal_56_2_1:any = this.parentView.context.endPoint.upstream_url;
    this._NgModel_56_7.check_model(currVal_56_2_1,throwOnChange,false);
    this._NgModel_56_7.ngDoCheck(this,this._el_56,throwOnChange);
    this._NgControlStatus_56_9.ngDoCheck(this,this._el_56,throwOnChange);
    this._DefaultValueAccessor_67_3.ngDoCheck(this,this._el_67,throwOnChange);
    const currVal_67_1_0:any = 'upstreamUsername';
    this._NgModel_67_5.check_name(currVal_67_1_0,throwOnChange,false);
    const currVal_67_1_1:any = this.parentView.context.endPoint.upstream_username;
    this._NgModel_67_5.check_model(currVal_67_1_1,throwOnChange,false);
    this._NgModel_67_5.ngDoCheck(this,this._el_67,throwOnChange);
    this._NgControlStatus_67_7.ngDoCheck(this,this._el_67,throwOnChange);
    this._DefaultValueAccessor_78_3.ngDoCheck(this,this._el_78,throwOnChange);
    const currVal_78_1_0:any = 'upstreamPassword';
    this._NgModel_78_5.check_name(currVal_78_1_0,throwOnChange,false);
    const currVal_78_1_1:any = this.parentView.context.endPoint.upstream_password;
    this._NgModel_78_5.check_model(currVal_78_1_1,throwOnChange,false);
    this._NgModel_78_5.ngDoCheck(this,this._el_78,throwOnChange);
    this._NgControlStatus_78_7.ngDoCheck(this,this._el_78,throwOnChange);
    const currVal_95_0_0:any = 'Api Keys';
    this._TabDirective_95_3.check_heading(currVal_95_0_0,throwOnChange,false);
    this._TabDirective_95_3.ngDoCheck(this,this._el_95,throwOnChange);
    const currVal_97_0_0:any = this.parentView.context.endPoint.apiKeys;
    this._ApiKeyListComponent_97_3.check_apiKeys(currVal_97_0_0,throwOnChange,false);
    this._ApiKeyListComponent_97_3.ngDoCheck(this,this._el_97,throwOnChange);
    this._TabsetComponent_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._TabDirective_4_3.checkHost(this,this,this._el_4,throwOnChange);
    this._NgControlStatusGroup_6_5.checkHost(this,this,this._el_6,throwOnChange);
    this._AccordionComponent_8_3.checkHost(this,this.compView_8,this._el_8,throwOnChange);
    this._AccordionPanelComponent_10_3.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    const currVal_145:any = import3.inlineInterpolate(1,'',this.parentView.context.endPoint.id,'');
    if (import3.checkBinding(throwOnChange,this._expr_145,currVal_145)) {
      this.renderer.setText(this._text_20,currVal_145);
      this._expr_145 = currVal_145;
    }
    this._RequiredValidator_31_4.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_42_7.checkHost(this,this,this._el_42,throwOnChange);
    this._AccordionPanelComponent_47_3.checkHost(this,this.compView_47,this._el_47,throwOnChange);
    this._RequiredValidator_56_4.checkHost(this,this,this._el_56,throwOnChange);
    this._NgControlStatus_56_9.checkHost(this,this,this._el_56,throwOnChange);
    this._NgControlStatus_67_7.checkHost(this,this,this._el_67,throwOnChange);
    this._NgControlStatus_78_7.checkHost(this,this,this._el_78,throwOnChange);
    this._TabDirective_95_3.checkHost(this,this,this._el_95,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_8.internalDetectChanges(throwOnChange);
    this.compView_10.internalDetectChanges(throwOnChange);
    this.compView_47.internalDetectChanges(throwOnChange);
    this.compView_97.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this.compView_8.destroy();
    this.compView_10.destroy();
    this.compView_47.destroy();
    this.compView_97.destroy();
    this._NgModel_31_7.ngOnDestroy();
    this._NgModel_42_5.ngOnDestroy();
    this._AccordionPanelComponent_10_3.ngOnDestroy();
    this._NgModel_56_7.ngOnDestroy();
    this._NgModel_67_5.ngOnDestroy();
    this._NgModel_78_5.ngOnDestroy();
    this._AccordionPanelComponent_47_3.ngOnDestroy();
    this._NgForm_6_3.ngOnDestroy();
    this._TabDirective_4_3.ngOnDestroy();
    this._TabDirective_95_3.ngOnDestroy();
    this._TabsetComponent_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_94,ctx);
      cb(this._el_95,ctx);
      cb(this._text_99,ctx);
    }
    if (((nodeIndex == 8) && (ngContentIndex == 0))) {
      cb(this._text_9,ctx);
      cb(this._el_10,ctx);
      cb(this._text_46,ctx);
      cb(this._el_47,ctx);
      cb(this._text_82,ctx);
    }
    if (((nodeIndex == 10) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 10) && (ngContentIndex == 1))) {
      cb(this._text_11,ctx);
      cb(this._el_12,ctx);
      cb(this._text_23,ctx);
      cb(this._el_24,ctx);
      cb(this._text_34,ctx);
      cb(this._el_35,ctx);
      cb(this._text_45,ctx);
    }
    if (((nodeIndex == 47) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 47) && (ngContentIndex == 1))) {
      cb(this._text_48,ctx);
      cb(this._el_49,ctx);
      cb(this._text_59,ctx);
      cb(this._el_60,ctx);
      cb(this._text_70,ctx);
      cb(this._el_71,ctx);
      cb(this._text_81,ctx);
    }
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_6_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_31_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.endPoint.title = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._CheckboxControlValueAccessor_42_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.endPoint.enabled = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_56(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_56_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.endPoint.upstream_url = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_67(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_67_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.endPoint.upstream_username = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_78(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_78_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.endPoint.upstream_password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_86(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.goBack()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_89(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_EndPointDetailComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_EndPointDetailComponent,{});
export class View_EndPointDetailComponent0 extends import1.AppView<import0.EndPointDetailComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import26.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import42.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EndPointDetailComponent0,renderType_EndPointDetailComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import26.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import43.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import42.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._anchor_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import44.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.endPoint;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_EndPointDetailComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}