/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './ApiKeyListComponent';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import11 from '@angular/core/src/linker/template_ref';
import * as import12 from '@angular/common/src/directives/ng_switch';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import15 from '@angular/common/src/directives/ng_for';
export class Wrapper_ApiKeyListComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ApiKeyListComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.ApiKeyListComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_apiKeys(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.apiKeys = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ApiKeyListComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ApiKeyListComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ApiKeyListComponent>;
  _ApiKeyListComponent_0_3:Wrapper_ApiKeyListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApiKeyListComponent_Host0,renderType_ApiKeyListComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'apiKey-list',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ApiKeyListComponent0(this.viewUtils,this,0,this._el_0);
    this._ApiKeyListComponent_0_3 = new Wrapper_ApiKeyListComponent();
    this.compView_0.create(this._ApiKeyListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ApiKeyListComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ApiKeyListComponent) && (0 === requestNodeIndex))) { return this._ApiKeyListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiKeyListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ApiKeyListComponentNgFactory:import8.ComponentFactory<import0.ApiKeyListComponent> = new import8.ComponentFactory<import0.ApiKeyListComponent>('apiKey-list',View_ApiKeyListComponent_Host0,import0.ApiKeyListComponent);
const styles_ApiKeyListComponent:any[] = ([] as any[]);
class View_ApiKeyListComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ApiKeyListComponent2,renderType_ApiKeyListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Developer',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ApiKeyListComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ApiKeyListComponent3,renderType_ApiKeyListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Application',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ApiKeyListComponent4 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ApiKeyListComponent4,renderType_ApiKeyListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray8(6,'class','fa fa-check','style','color:green','title','Enabled'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ApiKeyListComponent5 extends import2.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ApiKeyListComponent5,renderType_ApiKeyListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray8(6,'class','fa fa-times','style','color:red','title','Disabled'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ApiKeyListComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _NgSwitch_11_3:import10.Wrapper_NgSwitch;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import9.ViewContainer;
  _TemplateRef_13_5:any;
  _NgSwitchCase_13_6:import10.Wrapper_NgSwitchCase;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import9.ViewContainer;
  _TemplateRef_15_5:any;
  _NgSwitchDefault_15_6:import10.Wrapper_NgSwitchDefault;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _NgSwitch_18_3:import10.Wrapper_NgSwitch;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import9.ViewContainer;
  _TemplateRef_20_5:any;
  _NgSwitchCase_20_6:import10.Wrapper_NgSwitchCase;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import9.ViewContainer;
  _TemplateRef_22_5:any;
  _NgSwitchDefault_22_6:import10.Wrapper_NgSwitchDefault;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ApiKeyListComponent1,renderType_ApiKeyListComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_50 = import1.UNINITIALIZED;
    this._expr_51 = import1.UNINITIALIZED;
    this._expr_52 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_11_3 = new import10.Wrapper_NgSwitch();
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_13 = new import9.ViewContainer(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import11.TemplateRef_(this,13,this._anchor_13);
    this._NgSwitchCase_13_6 = new import10.Wrapper_NgSwitchCase(this._vc_13.vcRef,this._TemplateRef_13_5,this._NgSwitch_11_3.context);
    this._text_14 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_15 = new import9.ViewContainer(15,11,this,this._anchor_15);
    this._TemplateRef_15_5 = new import11.TemplateRef_(this,15,this._anchor_15);
    this._NgSwitchDefault_15_6 = new import10.Wrapper_NgSwitchDefault(this._vc_15.vcRef,this._TemplateRef_15_5,this._NgSwitch_11_3.context);
    this._text_16 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_18_3 = new import10.Wrapper_NgSwitch();
    this._text_19 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_20 = new import9.ViewContainer(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import11.TemplateRef_(this,20,this._anchor_20);
    this._NgSwitchCase_20_6 = new import10.Wrapper_NgSwitchCase(this._vc_20.vcRef,this._TemplateRef_20_5,this._NgSwitch_18_3.context);
    this._text_21 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_22 = new import9.ViewContainer(22,18,this,this._anchor_22);
    this._TemplateRef_22_5 = new import11.TemplateRef_(this,22,this._anchor_22);
    this._NgSwitchDefault_22_6 = new import10.Wrapper_NgSwitchDefault(this._vc_22.vcRef,this._TemplateRef_22_5,this._NgSwitch_18_3.context);
    this._text_23 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n          ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'button',new import3.InlineArray8(8,'aria-label','Delete','class','btn btn-default btn-xs','name','delete','type','button'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-trash'),(null as any));
    this._text_30 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Delete',(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_27));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import12.NgSwitchCase) && (13 === requestNodeIndex))) { return this._NgSwitchCase_13_6.context; }
    if (((token === import11.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import12.NgSwitchDefault) && (15 === requestNodeIndex))) { return this._NgSwitchDefault_15_6.context; }
    if (((token === import12.NgSwitch) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgSwitch_11_3.context; }
    if (((token === import11.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import12.NgSwitchCase) && (20 === requestNodeIndex))) { return this._NgSwitchCase_20_6.context; }
    if (((token === import11.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import12.NgSwitchDefault) && (22 === requestNodeIndex))) { return this._NgSwitchDefault_22_6.context; }
    if (((token === import12.NgSwitch) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgSwitch_18_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_11_0_0:any = this.context.$implicit.developer_key;
    this._NgSwitch_11_3.check_ngSwitch(currVal_11_0_0,throwOnChange,false);
    this._NgSwitch_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_13_0_0:any = true;
    this._NgSwitchCase_13_6.check_ngSwitchCase(currVal_13_0_0,throwOnChange,false);
    this._NgSwitchCase_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    this._NgSwitchDefault_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    const currVal_18_0_0:any = this.context.$implicit.enabled;
    this._NgSwitch_18_3.check_ngSwitch(currVal_18_0_0,throwOnChange,false);
    this._NgSwitch_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_20_0_0:any = true;
    this._NgSwitchCase_20_6.check_ngSwitchCase(currVal_20_0_0,throwOnChange,false);
    this._NgSwitchCase_20_6.ngDoCheck(this,this._anchor_20,throwOnChange);
    this._NgSwitchDefault_22_6.ngDoCheck(this,this._anchor_22,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    const currVal_50:any = import3.inlineInterpolate(1,'',this.context.$implicit.id,'');
    if (import3.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setText(this._text_3,currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = import3.inlineInterpolate(1,'',this.context.$implicit.user_title,'');
    if (import3.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setText(this._text_6,currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = import3.inlineInterpolate(1,'',this.context.$implicit.created_by,'');
    if (import3.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setText(this._text_9,currVal_52);
      this._expr_52 = currVal_52;
    }
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this._vc_15.destroyNestedViews();
    this._vc_20.destroyNestedViews();
    this._vc_22.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 13)) { return new View_ApiKeyListComponent2(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 15)) { return new View_ApiKeyListComponent3(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 20)) { return new View_ApiKeyListComponent4(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    if ((nodeIndex == 22)) { return new View_ApiKeyListComponent5(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    return (null as any);
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      this.parentView.context.delete(this.context.$implicit);
      const pd_sub_0:any = ((<any>$event.stopPropagation()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_ApiKeyListComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_ApiKeyListComponent,{});
export class View_ApiKeyListComponent0 extends import2.AppView<import0.ApiKeyListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import9.ViewContainer;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import13.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApiKeyListComponent0,renderType_ApiKeyListComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','no-footer table-responsive'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'table',new import3.InlineArray16(10,'cellpadding','0','cellspacing','0','class','table table-striped','role','table','style','width:100%'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'ID',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'User Title',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Type',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Enabled',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Actions',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_23 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import9.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import11.TemplateRef_(this,27,this._anchor_27);
    this._NgFor_27_6 = new import13.Wrapper_NgFor(this._vc_27.vcRef,this._TemplateRef_27_5,this.parentView.injectorGet(import14.IterableDiffers,this.parentIndex),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_30 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import15.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_27_0_0:any = this.context.apiKeys;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_27.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 27)) { return new View_ApiKeyListComponent1(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    return (null as any);
  }
}