/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from 'ng2-bootstrap/collapse/collapse.module';
import * as import9 from 'ng2-bootstrap/accordion/accordion.module';
import * as import10 from 'ng2-bootstrap/tabs/tabs.module';
import * as import11 from '@angular/router/src/router_module';
import * as import12 from './app-routing.module';
import * as import13 from 'angular-confirmation-popover/dist/esm/src/confirmationPopover.module';
import * as import14 from '@angular/common/src/localization';
import * as import15 from '@angular/core/src/application_init';
import * as import16 from '@angular/core/src/testability/testability';
import * as import17 from '@angular/core/src/application_ref';
import * as import18 from '@angular/core/src/linker/compiler';
import * as import19 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import20 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import21 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import22 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import23 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import24 from '@angular/core/src/animation/animation_queue';
import * as import25 from '@angular/core/src/linker/view_utils';
import * as import26 from '@angular/platform-browser/src/browser/title';
import * as import27 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import28 from '@angular/http/src/backends/browser_xhr';
import * as import29 from '@angular/http/src/base_response_options';
import * as import30 from '@angular/http/src/backends/xhr_backend';
import * as import31 from '@angular/http/src/base_request_options';
import * as import32 from '@angular/common/src/location/location';
import * as import33 from '@angular/router/src/url_tree';
import * as import34 from '@angular/router/src/router_outlet_map';
import * as import35 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import36 from '@angular/router/src/router_preloader';
import * as import37 from 'ng2-bootstrap/accordion/accordion.config';
import * as import38 from 'ng2-bootstrap/tabs/tabset.config';
import * as import39 from 'positioning/dist/umd/src/positioning';
import * as import40 from './EndPoint/EndPointService';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from './EndPoint/EndPointListMyComponent.ngfactory';
import * as import43 from './EndPoint/EndPointListComponent.ngfactory';
import * as import44 from './EndPoint/EndPointDetailComponent.ngfactory';
import * as import45 from '../node_modules/angular-confirmation-popover/dist/esm/src/confirmationPopoverWindow.component.ngfactory';
import * as import46 from './app.component.ngfactory';
import * as import47 from '@angular/core/src/i18n/tokens';
import * as import48 from '@angular/core/src/application_tokens';
import * as import49 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import50 from '@angular/platform-browser/src/dom/events/key_events';
import * as import51 from '@angular/core/src/zone/ng_zone';
import * as import52 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import53 from '@angular/common/src/location/platform_location';
import * as import54 from '@angular/common/src/location/location_strategy';
import * as import55 from './EndPoint/EndPointListMyComponent';
import * as import56 from './EndPoint/EndPointListComponent';
import * as import57 from './EndPoint/EndPointDetailComponent';
import * as import58 from '@angular/router/src/url_handling_strategy';
import * as import59 from '@angular/router/src/route_reuse_strategy';
import * as import60 from '@angular/router/src/router';
import * as import61 from '@angular/core/src/console';
import * as import62 from '@angular/core/src/error_handler';
import * as import63 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import64 from '@angular/platform-browser/src/dom/animation_driver';
import * as import65 from '@angular/core/src/render/api';
import * as import66 from '@angular/core/src/security';
import * as import67 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import68 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import69 from '@angular/http/src/interfaces';
import * as import70 from '@angular/http/src/http';
import * as import71 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import72 from '@angular/router/src/router_config_loader';
import * as import73 from '@angular/router/src/router_state';
import * as import74 from 'angular-confirmation-popover/dist/esm/src/confirmationPopoverOptions.provider';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _CollapseModule_6:import8.CollapseModule;
  _AccordionModule_7:import9.AccordionModule;
  _TabsModule_8:import10.TabsModule;
  _ROUTER_FORROOT_GUARD_9:any;
  _RouterModule_10:import11.RouterModule;
  _AppRoutingModule_11:import12.AppRoutingModule;
  _ConfirmationPopoverModule_12:import13.ConfirmationPopoverModule;
  _AppModule_13:import1.AppModule;
  __LOCALE_ID_14:any;
  __NgLocalization_15:import14.NgLocaleLocalization;
  _ErrorHandler_16:any;
  _ApplicationInitStatus_17:import15.ApplicationInitStatus;
  _Testability_18:import16.Testability;
  _ApplicationRef__19:import17.ApplicationRef_;
  __ApplicationRef_20:any;
  __Compiler_21:import18.Compiler;
  __APP_ID_22:any;
  __DOCUMENT_23:any;
  __HAMMER_GESTURE_CONFIG_24:import19.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_25:any[];
  __EventManager_26:import20.EventManager;
  __DomSharedStylesHost_27:import21.DomSharedStylesHost;
  __AnimationDriver_28:any;
  __DomRootRenderer_29:import22.DomRootRenderer_;
  __NgProbeToken_30:any[];
  __RootRenderer_31:any;
  __DomSanitizer_32:import23.DomSanitizerImpl;
  __Sanitizer_33:any;
  __AnimationQueue_34:import24.AnimationQueue;
  __ViewUtils_35:import25.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __SharedStylesHost_38:any;
  __Title_39:import26.Title;
  __RadioControlRegistry_40:import27.RadioControlRegistry;
  __BrowserXhr_41:import28.BrowserXhr;
  __ResponseOptions_42:import29.BaseResponseOptions;
  __XSRFStrategy_43:any;
  __XHRBackend_44:import30.XHRBackend;
  __RequestOptions_45:import31.BaseRequestOptions;
  __Http_46:any;
  __ROUTER_CONFIGURATION_47:any;
  __LocationStrategy_48:any;
  __Location_49:import32.Location;
  __UrlSerializer_50:import33.DefaultUrlSerializer;
  __RouterOutletMap_51:import34.RouterOutletMap;
  __NgModuleFactoryLoader_52:import35.SystemJsNgModuleLoader;
  __ROUTES_53:any[];
  __Router_54:any;
  __ActivatedRoute_55:any;
  _NoPreloading_56:import36.NoPreloading;
  _PreloadingStrategy_57:any;
  _RouterPreloader_58:import36.RouterPreloader;
  __PreloadAllModules_59:import36.PreloadAllModules;
  __ROUTER_INITIALIZER_60:any;
  __APP_BOOTSTRAP_LISTENER_61:any[];
  __AccordionConfig_62:import37.AccordionConfig;
  __TabsetConfig_63:import38.TabsetConfig;
  __USER_OPTIONS_64:any;
  __ConfirmationPopoverOptions_65:any;
  __Positioning_66:import39.Positioning;
  __EndPointService_67:import40.EndPointService;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.EndPointListMyComponentNgFactory,
      import43.EndPointListComponentNgFactory,
      import44.EndPointDetailComponentNgFactory,
      import45.ConfirmationPopoverWindowNgFactory,
      import46.AppComponentNgFactory
    ]
    ,[import46.AppComponentNgFactory]);
  }
  get _LOCALE_ID_14():any {
    if ((this.__LOCALE_ID_14 == null)) { (this.__LOCALE_ID_14 = import3._localeFactory(this.parent.get(import47.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_14;
  }
  get _NgLocalization_15():import14.NgLocaleLocalization {
    if ((this.__NgLocalization_15 == null)) { (this.__NgLocalization_15 = new import14.NgLocaleLocalization(this._LOCALE_ID_14)); }
    return this.__NgLocalization_15;
  }
  get _ApplicationRef_20():any {
    if ((this.__ApplicationRef_20 == null)) { (this.__ApplicationRef_20 = this._ApplicationRef__19); }
    return this.__ApplicationRef_20;
  }
  get _Compiler_21():import18.Compiler {
    if ((this.__Compiler_21 == null)) { (this.__Compiler_21 = new import18.Compiler()); }
    return this.__Compiler_21;
  }
  get _APP_ID_22():any {
    if ((this.__APP_ID_22 == null)) { (this.__APP_ID_22 = import48._appIdRandomProviderFactory()); }
    return this.__APP_ID_22;
  }
  get _DOCUMENT_23():any {
    if ((this.__DOCUMENT_23 == null)) { (this.__DOCUMENT_23 = import4._document()); }
    return this.__DOCUMENT_23;
  }
  get _HAMMER_GESTURE_CONFIG_24():import19.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_24 == null)) { (this.__HAMMER_GESTURE_CONFIG_24 = new import19.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_24;
  }
  get _EVENT_MANAGER_PLUGINS_25():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_25 == null)) { (this.__EVENT_MANAGER_PLUGINS_25 = [
      new import49.DomEventsPlugin(),
      new import50.KeyEventsPlugin(),
      new import19.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_24)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_25;
  }
  get _EventManager_26():import20.EventManager {
    if ((this.__EventManager_26 == null)) { (this.__EventManager_26 = new import20.EventManager(this._EVENT_MANAGER_PLUGINS_25,this.parent.get(import51.NgZone))); }
    return this.__EventManager_26;
  }
  get _DomSharedStylesHost_27():import21.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_27 == null)) { (this.__DomSharedStylesHost_27 = new import21.DomSharedStylesHost(this._DOCUMENT_23)); }
    return this.__DomSharedStylesHost_27;
  }
  get _AnimationDriver_28():any {
    if ((this.__AnimationDriver_28 == null)) { (this.__AnimationDriver_28 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_28;
  }
  get _DomRootRenderer_29():import22.DomRootRenderer_ {
    if ((this.__DomRootRenderer_29 == null)) { (this.__DomRootRenderer_29 = new import22.DomRootRenderer_(this._DOCUMENT_23,this._EventManager_26,this._DomSharedStylesHost_27,this._AnimationDriver_28,this._APP_ID_22)); }
    return this.__DomRootRenderer_29;
  }
  get _NgProbeToken_30():any[] {
    if ((this.__NgProbeToken_30 == null)) { (this.__NgProbeToken_30 = [import11.routerNgProbeToken()]); }
    return this.__NgProbeToken_30;
  }
  get _RootRenderer_31():any {
    if ((this.__RootRenderer_31 == null)) { (this.__RootRenderer_31 = import52._createConditionalRootRenderer(this._DomRootRenderer_29,this.parent.get(import52.NgProbeToken,(null as any)),this._NgProbeToken_30)); }
    return this.__RootRenderer_31;
  }
  get _DomSanitizer_32():import23.DomSanitizerImpl {
    if ((this.__DomSanitizer_32 == null)) { (this.__DomSanitizer_32 = new import23.DomSanitizerImpl()); }
    return this.__DomSanitizer_32;
  }
  get _Sanitizer_33():any {
    if ((this.__Sanitizer_33 == null)) { (this.__Sanitizer_33 = this._DomSanitizer_32); }
    return this.__Sanitizer_33;
  }
  get _AnimationQueue_34():import24.AnimationQueue {
    if ((this.__AnimationQueue_34 == null)) { (this.__AnimationQueue_34 = new import24.AnimationQueue(this.parent.get(import51.NgZone))); }
    return this.__AnimationQueue_34;
  }
  get _ViewUtils_35():import25.ViewUtils {
    if ((this.__ViewUtils_35 == null)) { (this.__ViewUtils_35 = new import25.ViewUtils(this._RootRenderer_31,this._Sanitizer_33,this._AnimationQueue_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _SharedStylesHost_38():any {
    if ((this.__SharedStylesHost_38 == null)) { (this.__SharedStylesHost_38 = this._DomSharedStylesHost_27); }
    return this.__SharedStylesHost_38;
  }
  get _Title_39():import26.Title {
    if ((this.__Title_39 == null)) { (this.__Title_39 = new import26.Title()); }
    return this.__Title_39;
  }
  get _RadioControlRegistry_40():import27.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == null)) { (this.__RadioControlRegistry_40 = new import27.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _BrowserXhr_41():import28.BrowserXhr {
    if ((this.__BrowserXhr_41 == null)) { (this.__BrowserXhr_41 = new import28.BrowserXhr()); }
    return this.__BrowserXhr_41;
  }
  get _ResponseOptions_42():import29.BaseResponseOptions {
    if ((this.__ResponseOptions_42 == null)) { (this.__ResponseOptions_42 = new import29.BaseResponseOptions()); }
    return this.__ResponseOptions_42;
  }
  get _XSRFStrategy_43():any {
    if ((this.__XSRFStrategy_43 == null)) { (this.__XSRFStrategy_43 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_43;
  }
  get _XHRBackend_44():import30.XHRBackend {
    if ((this.__XHRBackend_44 == null)) { (this.__XHRBackend_44 = new import30.XHRBackend(this._BrowserXhr_41,this._ResponseOptions_42,this._XSRFStrategy_43)); }
    return this.__XHRBackend_44;
  }
  get _RequestOptions_45():import31.BaseRequestOptions {
    if ((this.__RequestOptions_45 == null)) { (this.__RequestOptions_45 = new import31.BaseRequestOptions()); }
    return this.__RequestOptions_45;
  }
  get _Http_46():any {
    if ((this.__Http_46 == null)) { (this.__Http_46 = import7.httpFactory(this._XHRBackend_44,this._RequestOptions_45)); }
    return this.__Http_46;
  }
  get _ROUTER_CONFIGURATION_47():any {
    if ((this.__ROUTER_CONFIGURATION_47 == null)) { (this.__ROUTER_CONFIGURATION_47 = {}); }
    return this.__ROUTER_CONFIGURATION_47;
  }
  get _LocationStrategy_48():any {
    if ((this.__LocationStrategy_48 == null)) { (this.__LocationStrategy_48 = import11.provideLocationStrategy(this.parent.get(import53.PlatformLocation),this.parent.get(import54.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_47)); }
    return this.__LocationStrategy_48;
  }
  get _Location_49():import32.Location {
    if ((this.__Location_49 == null)) { (this.__Location_49 = new import32.Location(this._LocationStrategy_48)); }
    return this.__Location_49;
  }
  get _UrlSerializer_50():import33.DefaultUrlSerializer {
    if ((this.__UrlSerializer_50 == null)) { (this.__UrlSerializer_50 = new import33.DefaultUrlSerializer()); }
    return this.__UrlSerializer_50;
  }
  get _RouterOutletMap_51():import34.RouterOutletMap {
    if ((this.__RouterOutletMap_51 == null)) { (this.__RouterOutletMap_51 = new import34.RouterOutletMap()); }
    return this.__RouterOutletMap_51;
  }
  get _NgModuleFactoryLoader_52():import35.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_52 == null)) { (this.__NgModuleFactoryLoader_52 = new import35.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import35.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_52;
  }
  get _ROUTES_53():any[] {
      if ((this.__ROUTES_53 == null)) { (this.__ROUTES_53 = [[
        {
          path: '',
          redirectTo: 'endPoints/my',
          pathMatch: 'full'
        }
        ,
        {
          path: 'endPoints/my',
          component: import55.EndPointListMyComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'endPoints',
          component: import56.EndPointListComponent
        }
        ,
        {
          path: 'endPoints/:id',
          component: import57.EndPointDetailComponent
        }

      ]
    ]); }
    return this.__ROUTES_53;
  }
  get _Router_54():any {
    if ((this.__Router_54 == null)) { (this.__Router_54 = import11.setupRouter(this._ApplicationRef_20,this._UrlSerializer_50,this._RouterOutletMap_51,this._Location_49,this,this._NgModuleFactoryLoader_52,this._Compiler_21,this._ROUTES_53,this._ROUTER_CONFIGURATION_47,this.parent.get(import58.UrlHandlingStrategy,(null as any)),this.parent.get(import59.RouteReuseStrategy,(null as any)))); }
    return this.__Router_54;
  }
  get _ActivatedRoute_55():any {
    if ((this.__ActivatedRoute_55 == null)) { (this.__ActivatedRoute_55 = import11.rootRoute(this._Router_54)); }
    return this.__ActivatedRoute_55;
  }
  get _PreloadAllModules_59():import36.PreloadAllModules {
    if ((this.__PreloadAllModules_59 == null)) { (this.__PreloadAllModules_59 = new import36.PreloadAllModules()); }
    return this.__PreloadAllModules_59;
  }
  get _ROUTER_INITIALIZER_60():any {
    if ((this.__ROUTER_INITIALIZER_60 == null)) { (this.__ROUTER_INITIALIZER_60 = import11.initialRouterNavigation(this._Router_54,this._ApplicationRef_20,this._RouterPreloader_58,this._ROUTER_CONFIGURATION_47)); }
    return this.__ROUTER_INITIALIZER_60;
  }
  get _APP_BOOTSTRAP_LISTENER_61():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_61 == null)) { (this.__APP_BOOTSTRAP_LISTENER_61 = [this._ROUTER_INITIALIZER_60]); }
    return this.__APP_BOOTSTRAP_LISTENER_61;
  }
  get _AccordionConfig_62():import37.AccordionConfig {
    if ((this.__AccordionConfig_62 == null)) { (this.__AccordionConfig_62 = new import37.AccordionConfig()); }
    return this.__AccordionConfig_62;
  }
  get _TabsetConfig_63():import38.TabsetConfig {
    if ((this.__TabsetConfig_63 == null)) { (this.__TabsetConfig_63 = new import38.TabsetConfig()); }
    return this.__TabsetConfig_63;
  }
  get _USER_OPTIONS_64():any {
    if ((this.__USER_OPTIONS_64 == null)) { (this.__USER_OPTIONS_64 = {confirmButtonType: 'danger'}); }
    return this.__USER_OPTIONS_64;
  }
  get _ConfirmationPopoverOptions_65():any {
    if ((this.__ConfirmationPopoverOptions_65 == null)) { (this.__ConfirmationPopoverOptions_65 = import13.optionsFactory(this._USER_OPTIONS_64)); }
    return this.__ConfirmationPopoverOptions_65;
  }
  get _Positioning_66():import39.Positioning {
    if ((this.__Positioning_66 == null)) { (this.__Positioning_66 = new import39.Positioning()); }
    return this.__Positioning_66;
  }
  get _EndPointService_67():import40.EndPointService {
    if ((this.__EndPointService_67 == null)) { (this.__EndPointService_67 = new import40.EndPointService(this._Http_46)); }
    return this.__EndPointService_67;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._CollapseModule_6 = new import8.CollapseModule();
    this._AccordionModule_7 = new import9.AccordionModule();
    this._TabsModule_8 = new import10.TabsModule();
    this._ROUTER_FORROOT_GUARD_9 = import11.provideForRootGuard(this.parent.get(import60.Router,(null as any)));
    this._RouterModule_10 = new import11.RouterModule(this._ROUTER_FORROOT_GUARD_9);
    this._AppRoutingModule_11 = new import12.AppRoutingModule();
    this._ConfirmationPopoverModule_12 = new import13.ConfirmationPopoverModule();
    this._AppModule_13 = new import1.AppModule();
    this._ErrorHandler_16 = import4.errorHandler();
    this._ApplicationInitStatus_17 = new import15.ApplicationInitStatus(this.parent.get(import15.APP_INITIALIZER,(null as any)));
    this._Testability_18 = new import16.Testability(this.parent.get(import51.NgZone));
    this._ApplicationRef__19 = new import17.ApplicationRef_(this.parent.get(import51.NgZone),this.parent.get(import61.Console),this,this._ErrorHandler_16,this,this._ApplicationInitStatus_17,this.parent.get(import16.TestabilityRegistry,(null as any)),this._Testability_18);
    this._NoPreloading_56 = new import36.NoPreloading();
    this._PreloadingStrategy_57 = this._NoPreloading_56;
    this._RouterPreloader_58 = new import36.RouterPreloader(this._Router_54,this._NgModuleFactoryLoader_52,this._Compiler_21,this,this._PreloadingStrategy_57);
    return this._AppModule_13;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.CollapseModule)) { return this._CollapseModule_6; }
    if ((token === import9.AccordionModule)) { return this._AccordionModule_7; }
    if ((token === import10.TabsModule)) { return this._TabsModule_8; }
    if ((token === import11.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_9; }
    if ((token === import11.RouterModule)) { return this._RouterModule_10; }
    if ((token === import12.AppRoutingModule)) { return this._AppRoutingModule_11; }
    if ((token === import13.ConfirmationPopoverModule)) { return this._ConfirmationPopoverModule_12; }
    if ((token === import1.AppModule)) { return this._AppModule_13; }
    if ((token === import47.LOCALE_ID)) { return this._LOCALE_ID_14; }
    if ((token === import14.NgLocalization)) { return this._NgLocalization_15; }
    if ((token === import62.ErrorHandler)) { return this._ErrorHandler_16; }
    if ((token === import15.ApplicationInitStatus)) { return this._ApplicationInitStatus_17; }
    if ((token === import16.Testability)) { return this._Testability_18; }
    if ((token === import17.ApplicationRef_)) { return this._ApplicationRef__19; }
    if ((token === import17.ApplicationRef)) { return this._ApplicationRef_20; }
    if ((token === import18.Compiler)) { return this._Compiler_21; }
    if ((token === import48.APP_ID)) { return this._APP_ID_22; }
    if ((token === import63.DOCUMENT)) { return this._DOCUMENT_23; }
    if ((token === import19.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_24; }
    if ((token === import20.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_25; }
    if ((token === import20.EventManager)) { return this._EventManager_26; }
    if ((token === import21.DomSharedStylesHost)) { return this._DomSharedStylesHost_27; }
    if ((token === import64.AnimationDriver)) { return this._AnimationDriver_28; }
    if ((token === import22.DomRootRenderer)) { return this._DomRootRenderer_29; }
    if ((token === import17.NgProbeToken)) { return this._NgProbeToken_30; }
    if ((token === import65.RootRenderer)) { return this._RootRenderer_31; }
    if ((token === import23.DomSanitizer)) { return this._DomSanitizer_32; }
    if ((token === import66.Sanitizer)) { return this._Sanitizer_33; }
    if ((token === import24.AnimationQueue)) { return this._AnimationQueue_34; }
    if ((token === import25.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import67.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import68.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import21.SharedStylesHost)) { return this._SharedStylesHost_38; }
    if ((token === import26.Title)) { return this._Title_39; }
    if ((token === import27.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import28.BrowserXhr)) { return this._BrowserXhr_41; }
    if ((token === import29.ResponseOptions)) { return this._ResponseOptions_42; }
    if ((token === import69.XSRFStrategy)) { return this._XSRFStrategy_43; }
    if ((token === import30.XHRBackend)) { return this._XHRBackend_44; }
    if ((token === import31.RequestOptions)) { return this._RequestOptions_45; }
    if ((token === import70.Http)) { return this._Http_46; }
    if ((token === import11.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_47; }
    if ((token === import54.LocationStrategy)) { return this._LocationStrategy_48; }
    if ((token === import32.Location)) { return this._Location_49; }
    if ((token === import33.UrlSerializer)) { return this._UrlSerializer_50; }
    if ((token === import34.RouterOutletMap)) { return this._RouterOutletMap_51; }
    if ((token === import71.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_52; }
    if ((token === import72.ROUTES)) { return this._ROUTES_53; }
    if ((token === import60.Router)) { return this._Router_54; }
    if ((token === import73.ActivatedRoute)) { return this._ActivatedRoute_55; }
    if ((token === import36.NoPreloading)) { return this._NoPreloading_56; }
    if ((token === import36.PreloadingStrategy)) { return this._PreloadingStrategy_57; }
    if ((token === import36.RouterPreloader)) { return this._RouterPreloader_58; }
    if ((token === import36.PreloadAllModules)) { return this._PreloadAllModules_59; }
    if ((token === import11.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_60; }
    if ((token === import48.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_61; }
    if ((token === import37.AccordionConfig)) { return this._AccordionConfig_62; }
    if ((token === import38.TabsetConfig)) { return this._TabsetConfig_63; }
    if ((token === import13.USER_OPTIONS)) { return this._USER_OPTIONS_64; }
    if ((token === import74.ConfirmationPopoverOptions)) { return this._ConfirmationPopoverOptions_65; }
    if ((token === import39.Positioning)) { return this._Positioning_66; }
    if ((token === import40.EndPointService)) { return this._EndPointService_67; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__19.ngOnDestroy();
    this._RouterPreloader_58.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);