/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import9 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import10 from '@angular/core/src/linker/query_list';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/router/src/router_outlet_map';
import * as import18 from '@angular/core/src/linker/component_factory_resolver';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/router/src/directives/router_link_active';
import * as import21 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _RouterLinkWithHref_29_3:import8.Wrapper_RouterLinkWithHref;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _RouterLinkWithHref_41_3:import8.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_41_4:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_41_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_41_1:import10.QueryList<any>;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _RouterLinkWithHref_47_3:import8.Wrapper_RouterLinkWithHref;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  /*private*/ _vc_58:import11.ViewContainer;
  _RouterOutlet_58_5:import12.Wrapper_RouterOutlet;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _el_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _el_106:any;
  _el_107:any;
  _text_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _text_113:any;
  _el_114:any;
  _el_115:any;
  _text_116:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'header',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'nav',new import3.InlineArray4(4,'class','navbar navbar-default navbar-fixed-top','id','adminMainMenu'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n  \n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray16(12,'aria-controls','navbar','aria-expanded','false','class','navbar-toggle collapsed','data-target','#headerMenu','data-toggle','collapse','type','button'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Toggle navigation',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray4(4,'aria-hidden','true','class','icon-bar'),(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray4(4,'aria-hidden','true','class','icon-bar'),(null as any));
    this._text_16 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray4(4,'aria-hidden','true','class','icon-bar'),(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n  \n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','navbar-brand'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'a',new import3.InlineArray2(2,'href','http://www2.gov.bc.ca/'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'img',new import3.InlineArray4(4,'class','hidden-xs','src','images/gov3_bc_logo.png'),(null as any));
    this._text_25 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_22,'img',new import3.InlineArray4(4,'class','visible-xs-inline-block','src','images/gov3_bc_logo_mobile.png'),(null as any));
    this._text_27 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._text_28 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_20,'a',new import3.InlineArray2(2,'routerLink','/endPoints/my'),(null as any));
    this._RouterLinkWithHref_29_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_29,'span',new import3.InlineArray2(2,'class','navbar-brand-title'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'GW Admin',(null as any));
    this._text_32 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_34 = this.renderer.createText(this._el_4,'\n  \n      ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray8(6,'aria-expanded','false','class','navbar-collapse collapse','id','headerMenu'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-left'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n          ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'a',new import3.InlineArray8(6,'routerLink','/endPoints/my','routerLinkActive','active','title','My End Points'),(null as any));
    this._RouterLinkWithHref_41_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_41_4 = new import9.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_41),this.renderer);
    this._query_RouterLink_41_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_41_1 = new import10.QueryList<any>();
    this._text_42 = this.renderer.createText(this._el_41,'My End Points',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n          ',(null as any));
    this._text_44 = this.renderer.createText(this._el_37,'\n          ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_37,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'a',new import3.InlineArray4(4,'routerLink','/endPoints','title','All End Points'),(null as any));
    this._RouterLinkWithHref_47_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._text_48 = this.renderer.createText(this._el_47,'All End Points',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n          ',(null as any));
    this._text_50 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._text_52 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_54 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_55 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n  ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_58 = new import11.ViewContainer(58,56,this,this._el_58);
    this._RouterOutlet_58_5 = new import12.Wrapper_RouterOutlet(this.parentView.injectorGet(import17.RouterOutletMap,this.parentIndex),this._vc_58.vcRef,this.parentView.injectorGet(import18.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_59 = this.renderer.createText(this._el_56,'\n',(null as any));
    this._text_60 = this.renderer.createText(parentRenderNode,'\n    \n',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,parentRenderNode,'footer',new import3.InlineArray2(2,'class','footer'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n  ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'nav',new import3.InlineArray4(4,'class','navbar navbar-default navbar-fixed-bottom','id','footerMenu'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n    ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n      ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n\n        ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_67,'button',new import3.InlineArray16(12,'aria-controls','navbar','aria-expanded','false','class','navbar-toggle collapsed','data-target','#footerMenuBar','data-toggle','collapse','type','button'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'\n          ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_69,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'Toggle navigation',(null as any));
    this._text_73 = this.renderer.createText(this._el_69,'\n          ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_69,'span',new import3.InlineArray4(4,'aria-hidden','true','class','icon-bar'),(null as any));
    this._text_75 = this.renderer.createText(this._el_69,'\n          ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_69,'span',new import3.InlineArray4(4,'aria-hidden','true','class','icon-bar'),(null as any));
    this._text_77 = this.renderer.createText(this._el_69,'\n          ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_69,'span',new import3.InlineArray4(4,'aria-hidden','true','class','icon-bar'),(null as any));
    this._text_79 = this.renderer.createText(this._el_69,'\n        ',(null as any));
    this._text_80 = this.renderer.createText(this._el_67,'\n      ',(null as any));
    this._text_81 = this.renderer.createText(this._el_65,'\n\n      ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_65,'div',new import3.InlineArray8(6,'aria-expanded','false','class','navbar-collapse collapse','id','footerMenuBar'),(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'\n        ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_82,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-left'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_86,'a',new import3.InlineArray4(4,'href','http://www2.gov.bc.ca/gov/content/about-gov-bc-ca','title','About gov.bc.ca'),(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'About gov.bc.ca',(null as any));
    this._text_89 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_90,'a',new import3.InlineArray4(4,'href','http://www2.gov.bc.ca/gov/content/home/disclaimer','title','Disclaimer'),(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'Disclaimer',(null as any));
    this._text_93 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_94,'a',new import3.InlineArray4(4,'href','http://www2.gov.bc.ca/gov/content/home/privacy','title','Privacy'),(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'Privacy',(null as any));
    this._text_97 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_98,'a',new import3.InlineArray4(4,'href','http://www2.gov.bc.ca/gov/content/home/accessibility','title','Accessibility'),(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'Accessibility',(null as any));
    this._text_101 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_102 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_102,'a',new import3.InlineArray4(4,'href','http://www2.gov.bc.ca/gov/content/home/copyright','title','Copyright'),(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'Copyright',(null as any));
    this._text_105 = this.renderer.createText(this._el_84,'\n          ',(null as any));
    this._el_106 = import3.createRenderElement(this.renderer,this._el_84,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,this._el_106,'a',new import3.InlineArray4(4,'href','http://www2.gov.bc.ca/gov/content/home/contact-us','title','Contact Us'),(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'Contact Us',(null as any));
    this._text_109 = this.renderer.createText(this._el_84,'\n        ',(null as any));
    this._text_110 = this.renderer.createText(this._el_82,'\n      ',(null as any));
    this._text_111 = this.renderer.createText(this._el_65,'\n\n    ',(null as any));
    this._text_112 = this.renderer.createText(this._el_63,'\n  ',(null as any));
    this._text_113 = this.renderer.createText(this._el_61,'\n\n  ',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,this._el_61,'div',new import3.InlineArray2(2,'class','version'),(null as any));
    this._el_115 = import3.createRenderElement(this.renderer,this._el_114,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_116 = this.renderer.createText(this._el_61,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_29));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_41,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_41));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_47));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._el_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._el_106,
      this._el_107,
      this._text_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._text_113,
      this._el_114,
      this._el_115,
      this._text_116
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RouterLinkWithHref) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RouterLinkWithHref_29_3.context; }
    if (((token === import19.RouterLinkWithHref) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._RouterLinkWithHref_41_3.context; }
    if (((token === import20.RouterLinkActive) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._RouterLinkActive_41_4.context; }
    if (((token === import19.RouterLinkWithHref) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._RouterLinkWithHref_47_3.context; }
    if (((token === import21.RouterOutlet) && (58 === requestNodeIndex))) { return this._RouterOutlet_58_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_29_0_0:any = '/endPoints/my';
    this._RouterLinkWithHref_29_3.check_routerLink(currVal_29_0_0,throwOnChange,false);
    this._RouterLinkWithHref_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_41_0_0:any = '/endPoints/my';
    this._RouterLinkWithHref_41_3.check_routerLink(currVal_41_0_0,throwOnChange,false);
    this._RouterLinkWithHref_41_3.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_41_1_0:any = 'active';
    this._RouterLinkActive_41_4.check_routerLinkActive(currVal_41_1_0,throwOnChange,false);
    this._RouterLinkActive_41_4.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_47_0_0:any = '/endPoints';
    this._RouterLinkWithHref_47_3.check_routerLink(currVal_47_0_0,throwOnChange,false);
    this._RouterLinkWithHref_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    this._RouterOutlet_58_5.ngDoCheck(this,this._el_58,throwOnChange);
    this._vc_58.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_41_0.dirty) {
        this._query_RouterLink_41_0.reset(([] as any[]));
        this._RouterLinkActive_41_4.context.links = this._query_RouterLink_41_0;
        this._query_RouterLink_41_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_41_1.dirty) {
        this._query_RouterLinkWithHref_41_1.reset([this._RouterLinkWithHref_41_3.context]);
        this._RouterLinkActive_41_4.context.linksWithHrefs = this._query_RouterLinkWithHref_41_1;
        this._query_RouterLinkWithHref_41_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_41_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_29_3.checkHost(this,this,this._el_29,throwOnChange);
    this._RouterLinkWithHref_41_3.checkHost(this,this,this._el_41,throwOnChange);
    this._RouterLinkWithHref_47_3.checkHost(this,this,this._el_47,throwOnChange);
  }
  destroyInternal():void {
    this._vc_58.destroyNestedViews();
    this._RouterLinkWithHref_29_3.ngOnDestroy();
    this._RouterLinkWithHref_41_3.ngOnDestroy();
    this._RouterLinkActive_41_4.ngOnDestroy();
    this._RouterLinkWithHref_47_3.ngOnDestroy();
    this._RouterOutlet_58_5.ngOnDestroy();
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_29_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_41(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_41_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_47_3.handleEvent(eventName,$event) && result);
    return result;
  }
}